const{test}=require('node:test');const assert=require('node:assert/strict');
const C=require('../public/chess-intl'),T=require('../public/chess'),H=require('../public/checkers'),E=require('../public/checkers-intl'),F=require('../public/connect4'),R=require('../public/match-rules');
const empty=()=>Array.from({length:8},()=>Array(8).fill(null));
const rights=()=>({wK:true,wQ:true,bK:true,bQ:true});
function perft(board,color,ctx,depth){if(!depth)return 1;let n=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]?.[0]===color)for(const m of C.getLegalMoves(board,r,c,ctx)){const from={r,c},to={r:m.r,c:m.c};n+=perft(C.applyMove(board,r,c,to.r,to.c,m),color==='w'?'b':'w',C.nextContext(ctx,board[r][c],from,to,m),depth-1);}return n;}
function fen(text){return text.split('/').map(row=>{const out=[];for(const c of row){if(/\d/.test(c))out.push(...Array(+c).fill(null));else out.push((c===c.toUpperCase()?'w':'b')+c.toUpperCase());}return out;});}
function room(gameType='chess-intl',board=C.initialBoard()){return{gameType,board,currentPlayer:'w',castling:rights(),enPassant:null,moves:[],mustContinueFrom:null};}
function play(s,from,to,promotion){R.ensure(s);const p=s.board[from.r][from.c],engine=s.gameType==='chess-intl'?C:T;const m=engine.getLegalMoves(s.board,from.r,from.c,s).find(m=>m.r===to.r&&m.c===to.c&&(!m.promotion||m.promotion===(promotion||'Q')));assert.ok(m,'move must be legal');const capture=!!s.board[to.r][to.c]||!!m.enPassant;s.board=engine.applyMove(s.board,from.r,from.c,to.r,to.c,m);if(s.gameType==='chess-intl')Object.assign(s,C.nextContext(s,p,from,to,m));s.currentPlayer=s.currentPlayer==='w'?'b':'w';s.moves.push({from,to,piece:p,capture,special:m});R.record(s,p,capture,true);}
test('FIDE standard initial position has 20, 400, 8902 and 197281 legal leaves',()=>{for(const[d,n]of[[1,20],[2,400],[3,8902],[4,197281]])assert.equal(perft(C.initialBoard(),'w',{castling:rights(),enPassant:null},d),n);});
test('FIDE castling/tactical reference position perft: 48, 2039, 97862',()=>{const b=fen('r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R');for(const[d,n]of[[1,48],[2,2039],[3,97862]])assert.equal(perft(b,'w',{castling:rights(),enPassant:null},d),n);});
test('all four promotions work, preserve notation, and replay',()=>{const b=empty();b[7][7]='wK';b[0][7]='bK';b[1][0]='wP';assert.deepEqual(C.getLegalMoves(b,1,0,{}).filter(m=>m.r===0).map(m=>m.promotion),['Q','R','B','N']);for(const promotion of ['Q','R','B','N']){assert.equal(C.applyMove(b,1,0,0,0,{promotion})[0][0],'w'+promotion);assert.ok(C.moveNotation('wP',{r:1,c:0},{r:0,c:0},false,true,{promotion}).endsWith('='+promotion));}});
test('en passant cannot expose the king, and expires after one opposing move',()=>{const b=empty();b[3][7]='wK';b[0][0]='bK';b[3][0]='bR';b[3][4]='wP';b[3][3]='bP';assert.ok(!C.getLegalMoves(b,3,4,{enPassant:{r:2,c:3}}).some(m=>m.enPassant));assert.equal(C.nextContext({castling:rights(),enPassant:{r:2,c:3}},'wN',{r:7,c:1},{r:5,c:2},{}).enPassant,null);});
test('kings are never capturable in either chess engine',()=>{for(const engine of [C,T]){const b=empty();b[7][7]='wK';b[0][0]='bK';b[1][0]='wR';assert.ok(!engine.getLegalMoves(b,1,0,{}).some(m=>m.r===0&&m.c===0));}});
test('Thai setup, khon direction, met range and sixth-rank promotion',()=>{const initial=T.initialBoard();assert.equal(initial.flat().filter(Boolean).length,32);assert.equal(initial[5][0],'wP');assert.equal(initial[2][0],'bP');const b=empty();b[7][7]='wK';b[0][0]='bK';b[4][4]='wB';assert.deepEqual(T.getLegalMoves(b,4,4).map(m=>[m.r,m.c]).sort(),[[3,3],[3,4],[3,5],[5,3],[5,5]]);b[4][4]='wQ';assert.equal(T.getLegalMoves(b,4,4).length,4);b[3][2]='wP';assert.equal(T.applyMove(b,3,2,2,2)[2][2],'wQ');});
test('Thai flying kings land immediately beyond capture and can reverse in a chain',()=>{const b=empty();b[4][3]='wK';b[2][5]='bM';b[6][1]='bM';assert.deepEqual(H.getCaptureMoves(b,4,3).map(m=>[m.r,m.c]),[[1,6],[7,0]]);const after=H.applyMove(b,4,3,1,6).newBoard;assert.ok(H.getCaptureMoves(after,1,6).some(m=>m.r===7&&m.c===0));assert.equal(after[2][5],null);});
test('both checkers games force forward captures and end the turn on crowning',()=>{for(const engine of[H,E]){const b=empty();b[2][1]='wM';b[1][2]='bM';b[1][4]='bM';b[6][7]='wM';assert.deepEqual(engine.getLegalMoves(b,6,7,'w',null),[]);const result=engine.applyMove(b,2,1,0,3);assert.equal(result.promoted,true);assert.equal(result.newBoard[0][3],'wK');assert.equal(engine.canContinueCapture(result.newBoard,0,3,result.promoted),false);assert.ok(engine.canContinueCapture(result.newBoard,0,3));const backwards=empty();backwards[3][2]='wM';backwards[4][3]='bM';assert.equal(engine.getCaptureMoves(backwards,3,2).length,0);}});
test('English kings have only short steps; Thai kings have flying steps',()=>{const b=empty();b[3][4]='wK';assert.equal(E.getLegalMoves(b,3,4,'w').length,4);assert.ok(H.getLegalMoves(b,3,4,'w').length>4);});
test('repetition includes side, castling rights and only a legally usable en-passant square',()=>{const s=room();const key=R.positionKey(s);s.enPassant={r:2,c:3};assert.equal(R.positionKey(s),key);s.castling.wK=false;assert.notEqual(R.positionKey(s),key);s.castling.wK=true;s.currentPlayer='b';assert.notEqual(R.positionKey(s),key);const b=empty();b[7][7]='wK';b[0][0]='bK';b[3][4]='wP';b[3][3]='bP';const ep=room('chess-intl',b);const k=R.positionKey(ep);ep.enPassant={r:2,c:3};assert.notEqual(R.positionKey(ep),k);});
test('threefold is claimable before the announced move; fivefold is automatic; history survives old snapshots',()=>{const s=room();const cycle=[[{r:7,c:6},{r:5,c:5}],[{r:0,c:6},{r:2,c:5}],[{r:5,c:5},{r:7,c:6}],[{r:2,c:5},{r:0,c:6}]];for(let j=0;j<7;j++)play(s,...cycle[j%4]);const last=cycle[3];assert.equal(R.previewClaim(s,...last,{}),'threefold');assert.equal(R.claimReason(s),null);play(s,...last);assert.equal(R.claimReason(s),'threefold');assert.equal(R.automaticReason(s),null);const expected=JSON.stringify(s.drawState);delete s.drawState;assert.equal(JSON.stringify(R.ensure(s)),expected);for(let j=0;j<8;j++)play(s,...cycle[j%4]);assert.equal(R.automaticReason(s),'fivefold');});
test('50/75-move and English 40-move thresholds reset on capture or pawn/man movement',()=>{for(const[type,claim,limit]of[['chess-intl','fifty',100],['checkers-intl','forty',80]]){const s=room(type);R.ensure(s).quietPlies=limit;assert.equal(R.claimReason(s),claim);R.record(s,type==='chess-intl'?'wP':'wM',false,true);assert.equal(R.claimReason(s),null);}const s=room();R.ensure(s).quietPlies=150;assert.equal(R.automaticReason(s),'seventyfive');R.record(s,'wN',true,true);assert.equal(R.claimReason(s),null);});
test('dead material is distinct from not being able to force mate',()=>{const b=empty();b[7][7]='wK';b[0][0]='bK';const s=room('chess-intl',b);assert.equal(R.deadPosition(s),true);b[5][5]='wN';assert.equal(R.deadPosition(s),true);b[5][3]='wN';assert.equal(R.deadPosition(s),false);assert.equal(R.timeoutWinner(s,'b'),'w');assert.equal(R.timeoutWinner(s,'w'),null);});
test('Thai piece count starts after total pieces, preserves its original limit and gives the final reply',()=>{const b=empty();b[7][7]='wK';b[0][0]='bK';b[1][1]='bR';b[1][6]='bR';const s=room('chess',b);assert.deepEqual(R.countEligibility(s,'w'),{type:'pieces',limit:8,start:4});assert.ok(R.startCount(s,'w'));s.currentPlayer='b';R.record(s,'wK',false,true);assert.equal(s.drawState.count.value,5);s.board[1][1]=null;s.currentPlayer='w';R.record(s,'bR',false,true);assert.equal(s.drawState.count.limit,8);s.drawState.count.value=8;s.currentPlayer='b';assert.equal(R.automaticReason(s),null);s.currentPlayer='w';assert.equal(R.automaticReason(s),'counting');});
test('Thai counting uses khon priority before knights; no counting with unpromoted pawns',()=>{const b=empty();b[7][7]='wK';b[0][0]='bK';b[1][1]='bB';b[1][2]='bN';b[1][3]='bN';const s=room('chess',b);assert.equal(R.countEligibility(s,'w').limit,44);b[2][0]='bP';assert.equal(R.countEligibility(s,'w'),null);});
test('Connect Four validates columns, gravity, all four win directions and history replay',()=>{for(const c of[-1,7,1.5,undefined])assert.equal(F.findLandingRow(F.initialBoard(),c),-1);let b=F.initialBoard();for(let i=0;i<6;i++)b=F.applyMove(b,0,i%2?'b':'w');assert.equal(F.findLandingRow(b,0),-1);for(const[dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){const board=F.initialBoard();for(let i=0;i<4;i++)board[i*dr][3+i*dc]='Y';assert.equal(F.gameStatus(board).winner,'w');}assert.equal(F.applyMoves([{to:{r:5,c:2}},{to:{r:4,c:2}}])[4][2],'R');});
